# Generated by Django 4.2.4 on 2023-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lekhanapp', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='clik to read fulll post', max_length=255),
        ),
    ]
